export interface NpmPackageInfoAsDependency {
    /**
     * @type semver
     */
    version: string
    /**
     * @description npm package's verification id, generally generated by sha512 algorithm
     * 
     * @sample "sha512-a9gxpmdXtZEInkCSHUJDLHZVBgb1QS0jhss4cPP93EW7s+uC5bikET2twEF3KV+7rDblJcmNvTR7VJejqd2C2g=="
     */
    integrity: string,
    /**
     * @description whether used as devDependencies in npm project
     */
    dev: true,
    requires?: {
        [pkgname: string]: string/* semver */
    }
}