declare type NpmSemverString = string;
declare type FormattedSemverString = string;
export interface NpmPackageInfoAsDependency {
    /**
     * @type semver
     */
    version: string;
    /**
     * @description npm package's verification id, generally generated by sha512 algorithm
     *
     * @sample "sha512-a9gxpmdXtZEInkCSHUJDLHZVBgb1QS0jhss4cPP93EW7s+uC5bikET2twEF3KV+7rDblJcmNvTR7VJejqd2C2g=="
     */
    integrity: string;
    /**
     * @description whether used as devDependencies in npm project
     */
    dev: true;
    requires?: {
        [pkgname: string]: string;
    };
}
/**
 * @description structure to describte the FULL information about one package,
 * in general, returned by `https://registry.npmjs.com/[PKG]`
 */
export interface NpmPackageInfoIndex {
    name: string;
    "dist-tags": {
        /**
         * @sample "latest": "0.8.4"
         */
        [tagname: string]: FormattedSemverString;
    };
    versions: {
        [formatted_semver_key: string]: {
            name: NpmPackageInfoIndex['name'];
            version: FormattedSemverString;
            dependencies?: {
                /**
                 * @sample "@fibjs/mkdirp": "^1.0.1",
                 */
                [pkgname: string]: NpmSemverString;
            };
            devDependencies?: NpmPackageInfoIndex['versions'][any]['dependencies'];
            bin?: {
                /**
                 * @sample "fib-typify": "./bin/fib-typify.js"
                 */
                [bin_name: string]: string;
            };
            engines?: {
                /**
                 * @sample "fibjs": ">=0.28.0"
                 */
                [engine_name: string]: string;
            };
            dist: {
                /**
                 * @description one sha512 value to validate the package's integrity
                 */
                integrity: string;
                shasum: string;
                tarball: string;
                /**
                 * @description fileCount in tarball
                 */
                fileCount: number;
                /**
                 * @description size after tarball unpacked
                 */
                unpackedSize: number;
                /**
                 * @description signature for this version tarball generated by npm
                 */
                'npm-signature': string;
            };
        };
    };
    /**
     * @description latest modified date string
     */
    modified: string;
}
export {};
